export const USER_ACTION_TYPES = {
  USER_LOADING: "user/USER_LOADING",
  USER_SIGN_UP_SUCCEEDED: "user/USER_SIGN_UP_SUCCEEDED",
  USER_SIGN_UP_FAILED: "user/USER_SIGN_UP_FAILED",

  USER_SIGN_IN_FAILED: "user/USER_SIGN_IN_FAILED",
  USER_SIGN_IN_SUCCEEDED: "user/USER_SIGN_IN_SUCCEEDED",
  USER_SIGN_OUT: "user/USER_SIGN_OUT",
  FETCH_AUTH_STATUS: "user/FETCH_USER_STATUS",
  FETCH_AUTH_ERROR: "user/FETCH_USER_ERROR",
};
