export const USER_ACTION_TYPES = {
  USER_REGISTER_START: "user/USER_REGISTER_START",
  USER_REGISTER_FAILED: "user/USER_REGISTER_FAILED",
  USER_REGISTER_SUCCEEDED: "user/USER_REGISTER_SUCCEEDED",
  USER_SIGN_IN_START: "user/USER_SIGN_IN_START",
  USER_SIGN_IN_FAILED: "user/USER_SIGN_IN_FAILED",
  USER_SIGN_IN_SUCCEEDED: "user/USER_SIGN_IN_SUCCEEDED",
  USER_SIGN_OUT_START: "user/USER_SIGN_OUT_START",
  USER_SIGN_OUT_FAILED: "user/USER_SIGN_OUT_FAILED",
  USER_SIGN_OUT_SUCCEEDED: "user/USER_SIGN_OUT_SUCCEEDED",
  FETCH_AUTH_STATUS: "user/FETCH_USER_STATUS",
};
