export const POSTS_ACTION_TYPES = {
  FETCH_POSTS_START: "posts/FETCH_POSTS_START",
  FETCH_POSTS_FAILED: "posts/FETCH_POSTS_FAILED",
  FETCH_POSTS_SUCCEEDED: "posts/FETCH_POSTS_SUCCEEDED",
  FETCH_POST_START: "posts/FETCH_POST_START",
  FETCH_POST_FAILED: "posts/FETCH_POST_FAILED",
  FETCH_POST_SUCCEEDED: "posts/FETCH_POST_SUCCEEDED",
  CREATE_POST_START: "posts/CREATE_POST_START",
  CREATE_POST_FAILED: "posts/CREATE_POST_FAILED",
  CREATE_POST_SUCCEEDED: "posts/CREATE_POST_SUCCEEDED",
};
