export const ERROR_ACTION_TYPES = {
  SET_ERRORS: "error/SET_ERRORS",
  CLEAR_ERRORS: "error/CLEAR_ERRORS",
};

export const ERROR_IDS = {
  FETCH_POSTS_ERROR: "error/FETCH_POSTS_ERROR",
  FETCH_POST_ERROR: "error/FETCH_POST_ERROR",
  CREATE_POST_ERROR: "error/CREATE_POST_ERROR",
  DELETE_POST_ERROR: "error/DELETE_POST_ERROR",
  UPDATE_POST_ERROR: "error/UPDATE_POST_ERROR",
  CREATE_REVIEW_ERROR: "error/CREATE_REVIEW_ERROR",
  DELETE_REVIEW_ERROR: "error/DELETE_REVIEW_ERROR",
};
