export const ALERT_ACTION_TYPES = {
  SET_ERRORS: "alert/SET_ERRORS",
  SET_SUCCESS_ALERT: "alert/SET_SUCCESS_ALERT",
  CLEAR_ALERT: "alert/CLEAR_ALERT",
};

export const ALERT_TYPES = {
  ALERT_ERROR: "ALERT_ERROR",
  ALERT_SUCCESS: "ALERT_SUCCESS",
};
