export const ALERT_ACTION_TYPES = {
  SET_ERRORS: "alert/SET_ERRORS",
  SET_SUCCESS_ALERT: "alert/SET_SUCCESS_ALERT",
  CLEAR_ALERT: "alert/CLEAR_ALERT",
};

export const ERROR_IDS = {
  FETCH_POSTS_ERROR: "error/FETCH_POSTS_ERROR",
  FETCH_POST_ERROR: "error/FETCH_POST_ERROR",
  CREATE_POST_ERROR: "error/CREATE_POST_ERROR",
  DELETE_POST_ERROR: "error/DELETE_POST_ERROR",
  UPDATE_POST_ERROR: "error/UPDATE_POST_ERROR",
  CREATE_REVIEW_ERROR: "error/CREATE_REVIEW_ERROR",
  DELETE_REVIEW_ERROR: "error/DELETE_REVIEW_ERROR",
};

export const ALERT_TYPES = {
  ALERT_ERROR: "ALERT_ERROR",
  ALERT_SUCCESS: "ALERT_SUCCESS",
};
