export const POST_ACTION_TYPES = {
  POST_LOADING: "post/POST_LOADING",
  REVIEWS_LOADING: "post/REIVEWS_LOADING",
  POST_ACTION_FAILED: "post/POST_ACTION_FAILED",
  REVIEWS_ACTION_FAILED: "post/REVIEWS_ACTION_FAILED",
  FETCH_POST_SUCCEEDED: "post/FETCH_POST_SUCCEEDED",
  CREATE_POST_SUCCEEDED: "post/CREATE_POST_SUCCEEDED",
  DELETE_POST_SUCCEEDED: "post/DELETE_POST_SUCCEEDED",
  UPDATE_POST_SUCCEEDED: "post/UPDATE_POST_SUCCEEDED",
  CREATE_REVIEW_SUCCEEDED: "post/CREATE_REVIEW_SUCCEEDED",
  DELETE_REVIEW_SUCCEEDED: "post/DELETE_REVIEW_SUCCEEDED",
};
